# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-05 04:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_animal', models.CharField(max_length=100, verbose_name='Nome do Animal')),
                ('idade', models.IntegerField(default=0)),
                ('especie', models.CharField(max_length=100, verbose_name='Esp\xe9cie')),
                ('raca', models.CharField(max_length=100, verbose_name='Ra\xe7a')),
                ('observacao', models.CharField(blank=True, max_length=300, verbose_name='Observa\xe7\xe3o')),
            ],
        ),
        migrations.CreateModel(
            name='Doacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_doador', models.CharField(max_length=100, verbose_name='Nome do Doador')),
                ('tel_doador', models.CharField(max_length=100, verbose_name='Telefone do Doador')),
                ('tipo_doacao', models.CharField(choices=[('racao', 'Ra\xe7\xe3o'), ('med', 'Medicamentos')], max_length=15, verbose_name='Tipo de Doa\xe7\xe3o')),
                ('qntidade', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Historico_atendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_consulta', models.DateTimeField(verbose_name='Data da Consulta')),
                ('observacao', models.CharField(blank=True, max_length=300, verbose_name='Observa\xe7\xe3o')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Animal', verbose_name='animal')),
            ],
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_vet', models.CharField(max_length=100, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=30, verbose_name='Telefone')),
                ('crv', models.CharField(max_length=30, verbose_name='CRV')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endere\xe7o')),
            ],
        ),
        migrations.AddField(
            model_name='historico_atendimento',
            name='veterinario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Veterinario', verbose_name='veterin\xe1rio'),
        ),
    ]
